root = "/app"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]
  delay = 1000

[watcher]
  poll = true
  interval = 500

[log]
  color = true
  time = true
  level = "debug"

[screen]
  clear_on_rebuild = true
